In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
complete_df = pd.read_csv('./dataset/data_complete.csv')
training_df = pd.read_csv('./dataset/training.csv')
testing_df = pd.read_csv('./dataset/testing.csv')

In [4]:
complete_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [5]:
training_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [6]:
testing_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [16]:
numeric_data_complete = complete_df.select_dtypes(include=['float64','int64'])
categorical_columns_complete = complete_df.select_dtypes(include=['object'])

### Standardization

In [37]:
#Method_1
#
#numeric_data_complete
complete = np.array(numeric_data_complete)
# calculate mean  
complete_mean = complete.mean(axis=0)  
# calculate variance   
complete_std = complete.std(axis=0)  
# standardize  
complete1 = (complete-complete_mean)/complete_std  
# use function preprocessing.scale to standardize 
complete_scale = preprocessing.scale(complete)

In [38]:
complete_scale

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

In [40]:
#Method_2
X = np.array(numeric_data_complete)  
scaler = preprocessing.StandardScaler()  
X_scaled = scaler.fit_transform(X)

In [41]:
X_scaled

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

### Scaling features to a range

In [45]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=( -1, 1))
complete_minmax = min_max_scaler.fit_transform(complete)

In [46]:
complete_minmax

array([[-0.90654206, -0.14285714, -0.34530095, ...,  0.07692308,
        -0.46910219, -0.46910219],
       [-0.90654206, -0.14285714, -0.34530095, ...,  0.0678733 ,
        -0.25583421, -0.25583421],
       [-0.92523364, -0.14285714, -0.34530095, ...,  0.05882353,
         0.14569532,  0.14569532],
       ...,
       [-0.51401869, -0.71428571,  0.83949314, ...,  0.79788839,
         0.16795719,  0.16795719],
       [-0.23364486, -0.71428571,  0.83949314, ...,  0.79487179,
        -0.74725708, -0.74725708],
       [-0.21495327, -0.71428571,  0.83949314, ...,  0.7918552 ,
         0.36478114,  0.36478114]])

### Normalization

In [48]:
#Method_1
complete_normalized = preprocessing.normalize(complete, norm='l2')

In [49]:
complete_normalized

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])

In [52]:
#Method_2
normalizer = preprocessing.Normalizer().fit(complete)  # fit does nothing

In [53]:
normalizer

Normalizer(copy=True, norm='l2')

In [54]:
normalizer.transform(complete)

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])

Binarization

In [77]:
training_df['WeekStatus_Binarization'] = ''

In [78]:
training_df

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2,NSM,WeekStatus,Day_of_week,WeekStatus_Binarization
0,2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,...,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433,61200,Weekday,Monday,
1,2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,...,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195,61800,Weekday,Monday,
2,2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,...,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668,62400,Weekday,Monday,
3,2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,...,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097,63600,Weekday,Monday,
4,2016-01-11 17:50:00,50,40,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,...,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484,64200,Weekday,Monday,
5,2016-01-11 18:10:00,60,50,19.856667,45.560000,19.200000,44.500000,19.730000,44.900000,18.890000,...,91.833333,5.166667,40.000000,4.683333,33.039890,33.039890,65400,Weekday,Monday,
6,2016-01-11 18:20:00,60,40,19.790000,45.597500,19.200000,44.433333,19.730000,44.790000,18.890000,...,91.666667,5.333333,40.000000,4.666667,31.455702,31.455702,66000,Weekday,Monday,
7,2016-01-11 18:30:00,70,40,19.856667,46.090000,19.230000,44.400000,19.790000,44.863333,18.890000,...,91.500000,5.500000,40.000000,4.650000,3.089314,3.089314,66600,Weekday,Monday,
8,2016-01-11 19:00:00,430,50,20.133333,48.000000,19.566667,44.400000,19.890000,44.900000,19.000000,...,91.000000,6.000000,40.000000,4.600000,34.351142,34.351142,68400,Weekday,Monday,
9,2016-01-11 19:10:00,250,40,20.260000,52.726667,19.730000,45.100000,19.890000,45.493333,19.000000,...,90.500000,6.000000,40.000000,4.516667,19.205186,19.205186,69000,Weekday,Monday,
10,2016-01-11 19:20:00,100,10,20.426667,55.893333,19.856667,45.833333,20.033333,47.526667,19.000000,...,90.000000,6.000000,40.000000,4.433333,38.492071,38.492071,69600,Weekday,Monday,
11,2016-01-11 19:40:00,90,10,20.730000,52.660000,20.166667,47.223333,20.200000,48.530000,18.926667,...,89.000000,6.000000,40.000000,4.266667,35.880925,35.880925,70800,Weekday,Monday,
12,2016-01-11 20:00:00,80,30,20.890000,51.193333,20.200000,46.330000,20.200000,48.193333,18.963333,...,88.000000,6.000000,40.000000,4.100000,19.001759,19.001759,72000,Weekday,Monday,
13,2016-01-11 20:10:00,140,40,20.890000,49.800000,20.200000,46.026667,20.166667,47.633333,19.033333,...,87.833333,6.000000,40.000000,4.066667,38.872261,38.872261,72600,Weekday,Monday,
14,2016-01-11 20:20:00,120,20,20.890000,48.433333,20.200000,45.722500,20.166667,47.300000,19.175000,...,87.666667,6.000000,40.000000,4.033333,46.735262,46.735262,73200,Weekday,Monday,
15,2016-01-11 20:50:00,110,40,21.100000,46.596667,20.356667,44.963333,20.290000,46.633333,19.390000,...,87.166667,6.000000,40.000000,3.933333,6.277755,6.277755,75000,Weekday,Monday,
16,2016-01-11 21:00:00,110,30,21.133333,46.060000,20.426667,44.760000,20.290000,46.433333,19.390000,...,87.000000,6.000000,40.000000,3.900000,13.361033,13.361033,75600,Weekday,Monday,
17,2016-01-11 21:10:00,110,20,21.200000,45.800000,20.500000,44.760000,20.390000,46.223333,19.390000,...,87.166667,6.000000,40.000000,3.866667,19.305705,19.305705,76200,Weekday,Monday,
18,2016-01-11 21:20:00,100,30,21.290000,45.900000,20.533333,45.090000,20.390000,46.090000,19.390000,...,87.333333,6.000000,40.000000,3.833333,0.669517,0.669517,76800,Weekday,Monday,
19,2016-01-11 21:40:00,100,20,21.390000,45.690000,20.700000,45.060000,20.390000,46.090000,19.426667,...,87.666667,6.000000,40.000000,3.766667,43.484542,43.484542,78000,Weekday,Monday,
20,2016-01-11 21:50:00,100,20,21.500000,45.333333,20.700000,44.933333,20.390000,46.060000,19.566667,...,87.833333,6.000000,40.000000,3.733333,17.017450,17.017450,78600,Weekday,Monday,
21,2016-01-11 22:00:00,110,20,21.500000,45.126667,20.790000,44.633333,20.390000,46.000000,19.666667,...,88.000000,6.000000,40.000000,3.700000,24.104006,24.104006,79200,Weekday,Monday,
22,2016-01-11 22:10:00,400,20,21.533333,44.966667,20.790000,44.360000,20.426667,45.933333,19.600000,...,87.833333,6.166667,40.000000,3.716667,29.978291,29.978291,79800,Weekday,Monday,
23,2016-01-11 22:20:00,400,20,21.600000,44.766667,20.890000,44.223333,20.500000,45.933333,19.696667,...,87.666667,6.333333,40.000000,3.733333,24.677065,24.677065,80400,Weekday,Monday,
24,2016-01-11 22:30:00,390,30,21.600000,44.560000,20.963333,43.963333,20.500000,45.790000,20.096667,...,87.500000,6.500000,40.000000,3.750000,9.310880,9.310880,81000,Weekday,Monday,
25,2016-01-11 22:40:00,240,20,21.600000,44.360000,21.000000,43.833333,20.500000,45.730000,20.596667,...,87.333333,6.666667,40.000000,3.766667,41.368666,41.368666,81600,Weekday,Monday,
26,2016-01-11 23:00:00,60,20,21.600000,44.200000,21.000000,43.590000,20.417500,45.545000,21.166667,...,87.000000,7.000000,40.000000,3.800000,39.711993,39.711993,82800,Weekday,Monday,
27,2016-01-11 23:10:00,60,20,21.600000,44.200000,21.000000,43.590000,20.390000,45.663333,21.033333,...,87.833333,6.833333,37.000000,3.850000,5.397181,5.397181,83400,Weekday,Monday,
28,2016-01-11 23:20:00,50,10,21.600000,44.200000,21.000000,43.700000,20.290000,45.730000,20.963333,...,88.666667,6.666667,34.000000,3.900000,36.185547,36.185547,84000,Weekday,Monday,
29,2016-01-11 23:30:00,70,20,21.500000,44.230000,20.926667,43.760000,20.290000,45.790000,20.865000,...,89.500000,6.500000,31.000000,3.950000,20.563721,20.563721,84600,Weekday,Monday,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14773,2016-05-27 12:20:00,230,0,24.760000,47.926667,26.700000,40.018000,28.463333,43.360000,24.500000,...,64.666667,1.000000,51.333333,13.466667,19.176572,19.176572,44400,Weekday,Friday,
14774,2016-05-27 12:30:00,220,0,24.823333,47.790000,26.628571,40.090000,28.633333,43.060000,24.500000,...,63.500000,1.000000,44.500000,13.350000,48.908236,48.908236,45000,Weekday,Friday,
14775,2016-05-27 12:40:00,90,0,24.890000,47.790000,26.560000,40.236000,28.760000,42.800000,24.500000,...,62.333333,1.000000,37.666667,13.233333,12.211281,12.211281,45600,Weekday,Friday,
14776,2016-05-27 12:50:00,70,0,24.890000,47.790000,26.571429,40.384286,28.790000,42.430000,24.500000,...,61.166667,1.000000,30.833333,13.116667,28.464212,28.464212,46200,Weekday,Friday,
14777,2016-05-27 13:00:00,370,0,24.890000,47.730000,26.500000,40.460000,28.730000,42.156667,24.500000,...,60.000000,1.000000,24.000000,13.000000,48.686116,48.686116,46800,Weekday,Friday,
14778,2016-05-27 13:10:00,280,0,25.033333,48.363333,26.528571,40.595714,28.496667,41.900000,24.500000,...,59.833333,1.166667,23.666667,13.100000,32.420348,32.420348,47400,Weekday,Friday,
14779,2016-05-27 13:20:00,240,0,25.166667,48.156667,26.600000,40.940000,28.290000,41.966667,24.500000,...,59.666667,1.333333,23.333333,13.200000,49.189027,49.189027,48000,Weekday,Friday,
14780,2016-05-27 13:30:00,250,0,25.323333,47.930000,26.600000,41.012857,28.200000,42.090000,24.533333,...,59.500000,1.500000,23.000000,13.300000,15.081162,15.081162,48600,Weekday,Friday,
14781,2016-05-27 13:40:00,220,0,25.390000,47.656667,26.600000,41.036000,28.200000,42.030000,24.600000,...,59.333333,1.666667,22.666667,13.400000,45.226866,45.226866,49200,Weekday,Friday,
14782,2016-05-27 14:00:00,190,10,25.500000,47.060000,26.540000,41.000000,28.200000,41.530000,24.600000,...,59.000000,2.000000,22.000000,13.600000,41.515044,41.515044,50400,Weekday,Friday,
14783,2016-05-27 14:10:00,160,0,25.600000,46.990000,26.512500,41.203750,28.200000,41.590000,24.633333,...,59.000000,2.000000,21.833333,13.550000,19.540642,19.540642,51000,Weekday,Friday,
14784,2016-05-27 14:20:00,80,0,25.600000,46.730000,26.437143,41.384286,28.426667,41.430000,24.700000,...,59.000000,2.000000,21.666667,13.500000,16.977597,16.977597,51600,Weekday,Friday,
14785,2016-05-27 14:40:00,60,0,25.500000,46.360000,26.318571,41.264286,28.566667,40.663333,24.700000,...,59.000000,2.000000,21.333333,13.400000,40.409885,40.409885,52800,Weekday,Friday,
14786,2016-05-27 14:50:00,60,0,25.500000,46.060000,26.350000,41.000000,28.426667,40.590000,24.666667,...,59.000000,2.000000,21.166667,13.350000,37.889086,37.889086,53400,Weekday,Friday,
14787,2016-05-27 15:00:00,60,0,25.500000,45.933333,26.277143,41.000000,28.356667,40.560000,24.666667,...,59.000000,2.000000,21.000000,13.300000,17.123315,17.123315,54000,Weekday,Friday,
14788,2016-05-27 15:10:00,70,0,25.500000,45.760000,26.200000,41.000000,28.290000,40.433333,24.700000,...,58.333333,2.000000,21.333333,13.283333,24.058432,24.058432,54600,Weekday,Friday,
14789,2016-05-27 15:20:00,80,0,25.500000,45.626667,26.171429,41.000000,28.260000,40.260000,24.700000,...,57.666667,2.000000,21.666667,13.266667,9.538671,9.538671,55200,Weekday,Friday,
14790,2016-05-27 15:30:00,80,0,25.500000,45.590000,26.100000,41.000000,28.200000,40.126667,24.700000,...,57.000000,2.000000,22.000000,13.250000,30.020685,30.020685,55800,Weekday,Friday,
14791,2016-05-27 15:40:00,70,0,25.500000,45.522500,26.100000,41.051429,28.200000,40.200000,24.700000,...,56.333333,2.000000,22.333333,13.233333,23.851737,23.851737,56400,Weekday,Friday,
14792,2016-05-27 16:00:00,100,0,25.500000,45.730000,26.000000,41.428571,28.100000,40.433333,24.700000,...,55.000000,2.000000,23.000000,13.200000,18.215602,18.215602,57600,Weekday,Friday,
14793,2016-05-27 16:10:00,90,0,25.500000,45.790000,26.000000,41.590000,28.100000,40.560000,24.700000,...,55.000000,2.166667,22.833333,13.233333,38.751594,38.751594,58200,Weekday,Friday,
14794,2016-05-27 16:20:00,100,0,25.500000,45.933333,26.000000,41.652857,28.000000,40.700000,24.700000,...,55.000000,2.333333,22.666667,13.266667,32.306224,32.306224,58800,Weekday,Friday,
14795,2016-05-27 16:30:00,220,0,25.426667,46.060000,26.000000,41.700000,28.000000,40.760000,24.700000,...,55.000000,2.500000,22.500000,13.300000,23.009520,23.009520,59400,Weekday,Friday,
14796,2016-05-27 16:40:00,180,0,25.500000,46.530000,26.000000,41.725714,27.856667,40.500000,24.700000,...,55.000000,2.666667,22.333333,13.333333,25.296732,25.296732,60000,Weekday,Friday,
14797,2016-05-27 16:50:00,120,0,25.500000,47.456667,26.000000,42.320000,27.663333,40.693333,24.700000,...,55.000000,2.833333,22.166667,13.366667,1.796395,1.796395,60600,Weekday,Friday,
14798,2016-05-27 17:00:00,110,0,25.600000,47.193333,25.968571,42.528571,27.390000,41.030000,24.700000,...,55.000000,3.000000,22.000000,13.400000,18.248201,18.248201,61200,Weekday,Friday,
14799,2016-05-27 17:10:00,90,0,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,...,55.333333,3.166667,22.833333,13.366667,16.966162,16.966162,61800,Weekday,Friday,
14800,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,...,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940,63000,Weekday,Friday,
14801,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,...,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784,64200,Weekday,Friday,
14802,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,...,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851,64800,Weekday,Friday,

In [ ]:
fol row in training_df.rows:

In [84]:
training_df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'