In [2]:
import pandas as pds
# month_list = ['01','02'.....]
# for month int month_list:
#     month = i+1
#     filename_list = ['log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv','log'+year+month+'01.csv',]
# for filename in filename_list:
#     table = pds.read_csv(filename,low_memory=False)
#     copy
#     remove nan
#     remove outliers
#     replace nan
#     compute summary
#     delete date column and time column
#     save table_copy into csv
    
table = pds.read_csv('log20161201.csv',low_memory=False)

In [75]:
table_copy = table.copy(True)

In [66]:
table_copy.describe()

,zone,cik,code,size,idx,norefer,noagent,find,crawler
count,26127018.0,2.612702e+07,2.612689e+07,2.612702e+07,2.612689e+07,26127018.0,2.612702e+07,2.612689e+07,2.612689e+07
mean,0.0,6.423603e+18,2.367280e+02,1.094677e+05,2.610820e-01,0.0,7.151921e+00,9.742332e+00,5.988382e-02
std,0.0,2.820069e+21,6.649301e+01,1.110635e+06,4.392246e-01,0.0,3.309884e+03,1.319594e+00,2.372715e-01
min,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,1.000000e+00,0.000000e+00
25%,0.0,8.798150e+05,2.000000e+02,6.360000e+02,0.000000e+00,0.0,0.000000e+00,1.000000e+01,0.000000e+00
50%,0.0,1.111928e+06,2.000000e+02,6.165000e+03,0.000000e+00,0.0,0.000000e+00,1.000000e+01,0.000000e+00
75%,0.0,1.354457e+06,3.010000e+02,2.232400e+04,1.000000e+00,0.0,0.000000e+00,1.000000e+01,0.000000e+00
max,0.0,1.680396e+24,5.040000e+02,4.349652e+08,1.000000e+00,0.0,1.683174e+06,1.000000e+01,1.000000e+00

missing data:
    IP: if NaN, delete row
    date: if NaN, fill the most frequent date
    time: if NaN, fill with most frequent time
    zone: if NaN, fill 0
    cik: if NaN, delete row
    accession: if NaN, delete row
    extension: if NaN, delete row
    code: if NaN, fill 200
    size: if NaN, fill mean of size
    idx: if NaN, set 1
    norefer: if NaN, set 1 and 0 randomly according to their ratio
    noagent: if NaN, set 1 and 0 randomly according to their ratio
    find: if NaN, set 1 - 10 randomly according to their ratio
    crawler: if NaN, set 1 and 0 randomly according to their ratio
    browser: if NaN, set as 'ukn'

abnormal data:
    IP: 
    data: 
    time:
    zone:
    cik:
    accession:
    extension:
#    code: search through all possible HTTP status code, 
#    size: 4GB -> mean
#    idx:  > 1 or < 0 set 1
#    norefer: > 1 or < 0, set 1 and 0 randomly according to their ratio
#    noagent: > 1 or < 0, set 1 and 0 randomly according to their ratio
#    find: > 1 or < 0 set 1 - 10 randomly according to their ratio
#    crawler: > 1 or < 0, set 1 and 0 randomly according to their ratio
#    browser: out of bound, set 'ukn'

In [5]:
import numpy as np

In [6]:
table_copy.head()

,ip,date,time,zone,cik,accession,extention,code,size,idx,norefer,noagent,find,crawler,browser
0,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000043,.txt,200.0,5945.0,0.0,0.0,0.0,10.0,0.0,NaN
1,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-05-046448,.txt,200.0,113208.0,0.0,0.0,0.0,10.0,0.0,NaN
2,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-05-001069,.txt,200.0,117667.0,0.0,0.0,0.0,10.0,0.0,NaN
3,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-04-208260,.txt,200.0,128379.0,0.0,0.0,0.0,10.0,0.0,NaN
4,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000065,.txt,200.0,6917.0,0.0,0.0,0.0,10.0,0.0,NaN

In [7]:
#drop row if NaN found in column IP, cik, accession, or extension

,ip,date,time,zone,cik,accession,extention,code,size,idx,norefer,noagent,find,crawler,browser
0,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000043,.txt,200.0,5945.0,0.0,0.0,0.0,10.0,0.0,NaN
1,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-05-046448,.txt,200.0,113208.0,0.0,0.0,0.0,10.0,0.0,NaN
2,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-05-001069,.txt,200.0,117667.0,0.0,0.0,0.0,10.0,0.0,NaN
3,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-04-208260,.txt,200.0,128379.0,0.0,0.0,0.0,10.0,0.0,NaN
4,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000065,.txt,200.0,6917.0,0.0,0.0,0.0,10.0,0.0,NaN
5,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000050,.txt,200.0,6916.0,0.0,0.0,0.0,10.0,0.0,NaN
6,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000042,.txt,200.0,5945.0,0.0,0.0,0.0,10.0,0.0,NaN
7,100.36.243.bch,2016-12-01,00:00:00,0.0,1275152.0,0001193125-04-157619,.txt,200.0,142418.0,0.0,0.0,0.0,10.0,0.0,NaN
8,100.36.243.bch,2016-12-01,00:00:00,0.0,1186111.0,0000933590-10-000045,.txt,200.0,5946.0,0.0,0.0,0.0,10.0,0.0,NaN
9,104.155.131.ihh,2016-12-01,00:00:00,0.0,313180.0,0001387131-16-008216,-index.htm,301.0,629.0,1.0,0.0,0.0,10.0,0.0,NaN
10,104.155.175.fbb,2016-12-01,00:00:00,0.0,1636879.0,0001660657-16-000103,-index.htm,301.0,632.0,1.0,0.0,0.0,10.0,0.0,NaN
11,104.190.216.ced,2016-12-01,00:00:00,0.0,38264.0,0001003297-10-000107,.txt,301.0,594.0,0.0,0.0,0.0,10.0,0.0,NaN
12,104.190.216.ced,2016-12-01,00:00:00,0.0,38264.0,0001003297-10-000107,.txt,200.0,608311.0,0.0,0.0,0.0,10.0,0.0,NaN
13,107.77.202.cje,2016-12-01,00:00:00,0.0,1644406.0,0001628280-16-021589,hostess-8xkforrefinancing.htm,200.0,5628.0,0.0,0.0,0.0,9.0,0.0,NaN
14,108.39.205.jga,2016-12-01,00:00:00,0.0,97210.0,0001193125-10-120597,-index.htm,200.0,8963.0,1.0,0.0,0.0,10.0,0.0,NaN
15,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0000097216-10-000205,-index.htm,200.0,7797.0,1.0,0.0,0.0,10.0,0.0,NaN
16,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0000097216-08-000214,-index.htm,200.0,8834.0,1.0,0.0,0.0,10.0,0.0,NaN
17,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0000097216-08-000151,-index.htm,200.0,8096.0,1.0,0.0,0.0,10.0,0.0,NaN
18,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0001144204-08-012125,-index.htm,200.0,9282.0,1.0,0.0,0.0,10.0,0.0,NaN
19,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0000097216-09-000110,-index.htm,200.0,7809.0,1.0,0.0,0.0,10.0,0.0,NaN
20,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0001144204-09-011131,-index.htm,200.0,9610.0,1.0,0.0,0.0,10.0,0.0,NaN
21,108.39.205.jga,2016-12-01,00:00:00,0.0,97216.0,0000097216-08-000273,-index.htm,200.0,8097.0,1.0,0.0,0.0,10.0,0.0,NaN
22,115.193.189.cih,2016-12-01,00:00:00,0.0,702165.0,0001225208-16-042391,xslF345X02/doc3.xml,301.0,628.0,0.0,0.0,0.0,10.0,0.0,NaN
23,116.236.230.ccg,2016-12-01,00:00:00,0.0,1045546.0,0001193125-16-779734,R29.htm,200.0,102270.0,0.0,0.0,0.0,10.0,0.0,NaN
24,116.236.230.ccg,2016-12-01,00:00:00,0.0,27419.0,0000027419-16-000066,R24.htm,200.0,8389.0,0.0,0.0,0.0,10.0,0.0,NaN
25,117.89.49.jic,2016-12-01,00:00:00,0.0,700923.0,0001214659-16-015061,-index.htm,200.0,2810.0,1.0,0.0,0.0,10.0,0.0,NaN
26,117.89.49.jic,2016-12-01,00:00:00,0.0,1142596.0,0001564590-16-029639,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
27,117.89.49.jic,2016-12-01,00:00:00,0.0,1326583.0,0000947871-16-001731,-index.htm,301.0,639.0,1.0,0.0,0.0,10.0,0.0,NaN
28,117.89.49.jic,2016-12-01,00:00:00,0.0,108985.0,0000108985-16-000237,-index.htm,301.0,633.0,1.0,0.0,0.0,10.0,0.0,NaN
29,117.89.49.jic,2016-12-01,00:00:00,0.0,1421182.0,0001193125-16-779663,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26126988,66.249.91.ede,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-653754,-index.htm,200.0,3194.0,1.0,0.0,0.0,10.0,0.0,NaN
26126989,66.249.91.ede,2016-12-01,23:59:59,0.0,1058057.0,0001193125-14-433564,-index.htm,200.0,3202.0,1.0,0.0,0.0,10.0,0.0,NaN
26126990,66.249.91.ffb,2016-12-01,23:59:59,0.0,1058057.0,0001193125-15-107187,-index.htm,200.0,3311.0,1.0,0.0,0.0,10.0,0.0,NaN
26126991,66.249.91.ffb,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-653778,-index.htm,200.0,3297.0,1.0,0.0,0.0,10.0,0.0,NaN
26126992,66.249.91.ffb,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-678135,-index.htm,200.0,3201.0,1.0,0.0,0.0,10.0,0.0,NaN
26126993,66.249.91.gch,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-678143,-index.htm,200.0,2828.0,1.0,0.0,0.0,10.0,0.0,NaN
26126994,66.249.91.gch,2016-12-01,23:59:59,0.0,1058057.0,0001193125-15-213442,-index.htm,200.0,3200.0,1.0,0.0,0.0,10.0,0.0,NaN
26126995,66.249.91.gee,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-678135,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
26126996,66.249.91.gee,2016-12-01,23:59:59,0.0,1058057.0,0001193125-14-433564,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
26126997,66.249.91.gee,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-653770,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
26126998,66.249.91.gfj,2016-12-01,23:59:59,0.0,1058057.0,0001193125-16-653754,-index.htm,301.0,640.0,1.0,0.0,0.0,10.0,0.0,NaN
26126999,67.132.198.ddh,2016-12-01,23:59:59,0.0,1511337.0,0001511337-16-000282,rlj-2015123110k.htm,200.0,195726.0,0.0,0.0,0.0,9.0,0.0,NaN
26127000,68.180.230.eca,2016-12-01,23:59:59,0.0,315709.0,0000000000-07-054464,filename1.pdf,301.0,611.0,0.0,0.0,0.0,10.0,0.0,NaN
26127001,68.180.230.eca,2016-12-01,23:59:59,0.0,1316656.0,0001209191-15-015444,xslF345X03/doc4.xml,200.0,4247.0,0.0,0.0,0.0,10.0,0.0,NaN
26127002,68.180.230.eca,2016-12-01,23:59:59,0.0,18349.0,0000914062-10-000467,xslF345X03/edgar.xml,200.0,3623.0,0.0,0.0,0.0,10.0,0.0,NaN
26127003,68.180.230.eca,2016-12-01,23:59:59,0.0,714310.0,0000714310-07-000088,doc.xml,200.0,2219.0,0.0,0.0,0.0,10.0,0.0,NaN
26127004,68.180.230.eca,2016-12-01,23:59:59,0.0,1290900.0,0000899243-16-015376,doc4.xml,200.0,1653.0,0.0,0.0,0.0,10.0,0.0,NaN
26127005,68.180.230.eca,2016-12-01,23:59:59,0.0,51548.0,0000925751-04-000220,cfocert.htm,301.0,609.0,0.0,0.0,0.0,10.0,0.0,NaN
26127006,68.180.230.eca,2016-12-01,23:59:59,0.0,1010643.0,0000948221-03-000085,-index.htm,200.0,2829.0,1.0,0.0,0.0,10.0,0.0,NaN
26127007,68.180.230.eca,2016-12-01,23:59:59,0.0,27996.0,0001218164-08-000063,xslF345X03/edgar.xml,200.0,3573.0,0.0,0.0,0.0,10.0,0.0,NaN
26127008,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278072.0,0001071787-05-000403,.txt,301.0,603.0,0.0,0.0,0.0,10.0,0.0,NaN
26127009,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278064.0,0001056404-05-001632,.txt,301.0,604.0,0.0,0.0,0.0,10.0,0.0,NaN
26127010,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278063.0,0001056404-05-001635,.txt,301.0,604.0,0.0,0.0,0.0,10.0,0.0,NaN
26127011,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278072.0,0001071787-05-000403,.txt,200.0,20227.0,0.0,0.0,0.0,10.0,0.0,NaN
26127012,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278064.0,0001056404-05-001632,.txt,200.0,72133.0,0.0,0.0,0.0,10.0,0.0,NaN
26127013,68.181.177.ihd,2016-12-01,23:59:59,0.0,1278063.0,0001056404-05-001635,.txt,200.0,35389.0,0.0,0.0,0.0,10.0,0.0,NaN
26127014,74.73.231.igh,2016-12-01,23:59:59,0.0,1612720.0,0001213900-15-000835,.txt,200.0,26111.0,0.0,0.0,0.0,10.0,0.0,NaN
26127015,88.240.188.jhf,2016-12-01,23:59:59,0.0,1288776.0,0001288776-15-000023,goog10-qq12015.htm,200.0,75678.0,0.0,0.0,0.0,10.0,0.0,NaN
26127016,88.240.188.jhf,2016-12-01,23:59:59,0.0,1288776.0,0001288776-15-000023,goog10-qq12015.htm,301.0,622.0,0.0,0.0,0.0,10.0,0.0,NaN
26127017,98.110.173.iji,2016-12-01,23:59:59,0.0,1384365.0,0001393905-15-000477,-index.htm,200.0,10166.0,1.0,0.0,0.0,10.0,0.0,NaN

In [44]:
# get most frequent time
import random
row_counts = len(table_copy.index)
def get_most_freq_time():
    table_copy['datetime'] = table_copy['date'] + ' ' + table_copy['time']
    pds.to_datetime(table_copy['datetime'])
    df_time_as_index = table_copy.set_index('datetime',drop=True)
    df_time_as_index.index = pds.to_datetime(df_time_as_index.index)
    period = df_time_as_index.to_period('H')
    datetime_freq = pds.value_counts(period.index)
    most_freq_datetime = datetime_freq.to_timestamp().index[0]
    return most_freq_datetime

def get_random_norefer():
    total_counts = pds.value_counts(table_copy['norefer'])
    ratio_of_index1 = total_counts[0]/row_counts
    random_number = random.randint(0,10)
    if random_number <= ratio_of_index1 * 10:
        return total_counts.index[0]
    else:
        return 1 - total_counts.index[0]
    
def get_random_zero_or_one(column_name):
    total_counts = pds.value_counts(table_copy[column_name])
    ratio_of_index1 = total_counts[0]/row_counts
    random_number = random.randint(0,10)
    if random_number <= ratio_of_index1 * 10:
        return total_counts.index[0]
    else:
        return 1 - total_counts.index[0]
    
def replaceAll_outlier_withNaN():
    table_copy['noagent'] = np.where(np.abs(table_copy['noagent'] - 0.5) != 0.5,np.nan,table_copy['noagent'])
    table_copy['norefer'] = np.where(np.abs(table_copy['norefer'] - 0.5) != 0.5,np.nan,table_copy['norefer'])
    table_copy['crawler'] = np.where(np.abs(table_copy['crawler'] - 0.5) != 0.5,np.nan,table_copy['crawler'])
    table_copy['idx'] = np.where(np.abs(table_copy['idx'] - 0.5) != 0.5,np.nan,table_copy['idx'])
    table_copy['size'] = np.where(table_copy['size'] > 10000000,np.nan,table_copu['size'])
    #find outliers
    list_0_to_10 = np.arange(11)
    check_find = np.logical_not(np.isin(table_copy['find'],list_0_to_10))
    table_copy['find'] = np.where(check_find,np.nan,table_copy['find'])
    #browser outliers
    list_browser = ['mie','fox','saf','chr','sea','opr','oth','win','mac','lin','iph','ipd','and','rim','iem']
    check_browser = np.logical_not(np.isin(table_copy['browser'],list_browser))
    table_copy['browser'] = np.where(check_browser,np.nan,table_copy['browser'])
    #code outliers
    list_httpcode = [100,101,102,200,201,202,203,204,205,206,207,208,226,300,301,302,303,304,305,306,307,308,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,420,421,422,423,424,425,426,428,429,431,444,450,451,494,500,501,502,503,504,505,506,507,508,510,511]
    check_code = np.logical_not(np.isin(table_copy['code'],list_httpcode))
    table_copy['code'] = np.where(check_code,np.nan,table_copy['code'])
    
def drop_replace_nan():
    table_copy = table_copy.dropna(subset=['ip','cik','accession','extention'])
    mean_of_size = np.mean(table_copy['size'])
    fill_values = {'datetime':most_freq_datetime,'zone':0,'code':200,'size': mean_of_size,'idx':1,'browser':'ukn','norefer':get_random_zero_or_one('norefer'),'noagent':get_random_zero_or_one('noagent'),'crawler':get_random_zero_or_one('crawler'),'find':0}
    table_copy = table_copy.fillna(value=fill_values)

In [45]:
most_freq_datetime = get_most_freq_time()

In [49]:
#not yet finished!!!

In [72]:
table_copy['noagent'] = np.where(belongs_to_01(table_copy['noagent']), np.nan, table_copy['noagent'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [67]:
pds.value_counts(table_copy['noagent'])

0.0          25935060
1.0            191833
1683174.0          62
1405464.0          26
1316517.0          24
1356949.0           2
1555122.0           1
1540465.0           1
1335102.0           1
1319643.0           1
1188283.0           1
1126936.0           1
1108329.0           1
836412.0            1
715072.0            1
710826.0            1
21175.0             1
Name: noagent, dtype: int64

In [70]:
pds.value_counts(table_copy['code'])

200.0    17411130
301.0     6661066
404.0     1564578
0.0        300093
304.0       74966
206.0       33459
403.0       31010
429.0       26381
503.0       23124
504.0         568
500.0         489
400.0          21
502.0           8
Name: code, dtype: int64

In [95]:
pds.value_counts(table_copy['browser'])

200         58
50.22.49    55
301          5
180.76.1     2
20161201     2
202.90.2     2
172.250.     1
99.238.1     1
123.125.     1
Name: browser, dtype: int64

In [102]:
pds.value_counts(table_copy['code'])

200.0    17411130
301.0     6661066
404.0     1564578
0.0        300093
304.0       74966
206.0       33459
403.0       31010
429.0       26381
503.0       23124
504.0         568
500.0         489
400.0          21
502.0           8
Name: code, dtype: int64

In [84]:
list_01 = [0,1]
test1 = np.logical_not(np.isin(table_copy['noagent'],list_01))

In [94]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
list_01 = [0,1]
test1 = np.logical_not(np.isin(table_copy['noagent'],list_01))
table_copy['noagent'] = np.where(test1,np.nan,table_copy['noagent'])

In [99]:
list_browser = ['mie','fox','saf','chr','sea','opr','oth','win','mac','lin','iph','ipd','and','rim','iem']
test2 = test1 = np.logical_not(np.isin(table_copy['browser'],list_browser))
table_copy['browser'] = np.where(test2,np.nan,table_copy['browser'])

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [103]:
import logging

In [ ]:
logging.b